# Global configuration
global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds (default is 1 minute)
  evaluation_interval: 15s  # Evaluate rules every 15 seconds (default is 1 minute)
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files: 
    - "recording_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: "Development"
    
    # Use EC2 service discovery for dynamic instance detection
    ec2_sd_configs:
      - region: "ap-south-1"
        port: 9182

    relabel_configs:
      # Extract EC2 tag 'Name' as 'instance_name' label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name

      # Extract EC2 instance type as 'instance_type' label
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type