groups:
  - name: cpu_usage
    interval: 30s  # Rule evaluation interval
    rules:
      - record: instance:cpu_usage:percentage
        expr: (irate(windows_cpu_time_total{mode="idle"}[5m]))
        
      - record: instance:memory_usage:percentage
        expr: 100 - (windows_memory_physical_free_bytes{} / windows_memory_physical_total_bytes{}) * 100

      - record: instance:disk_usage:percentage 
        expr: 100 - (windows_logical_disk_free_bytes{} / windows_logical_disk_size_bytes{}) * 100
